#!/bin/bash
# rename-test

# Vars group

# Points
totalpoints=1
pospoints=2
negpoints=1


# Colors
ERRCOLOR=`tput setaf 1`
QCOLOR=`tput setaf 3`
ANSCOLOR=`tput setaf 2`
OUTCOLOR=`tput setaf 4`
PROMPTCOLOR=`tput setaf 3`
CMDCOLOR=`tput setaf 4`
COLRESET=`tput sgr0`

PROMPT="${COLRESET}codio ~/workspace $ ${COLRESET}"

# Helper funcs
function addpoints {
	totalpoints=$(($totalpoints+$pospoints))
	echo "${PROMPTCOLOR}=>${QCOLOR} Totalpoints: $totalpoints ${COLRESET}"
}
function substractpoints {
	totalpoints=$(($totalpoints-$negpoints))
	echo "${PROMPTCOLOR}=>${QCOLOR} Totalpoints: $totalpoints ${COLRESET}"
}
function changedir {
	cd "$1"
}
function goodbye {
	echo "${PROMPTCOLOR}=>${QCOLOR} Moving files and directories using the CLI saves you a lot of development time.${COLRESET}"
	addpoints
	echo "${PROMPTCOLOR}=>${QCOLOR} Keep on going with the CLI course, see you next time!${COLRESET}"
	exit
}

function question1 {
	if [[ -d "test-website/" ]]; then
		rm -r test-website
	fi
	if [[ -d "config/" ]]; then
		rm -r config
	fi
	if [[ ! -d "test-website/" ]]; then
		mkdir test-website/
		mkdir test-website/img
		mkdir test-website/config/
		touch test-website/index.html
		touch test-website/img/logo.png
		touch test-website/.website-config
	fi
	echo "${PROMPTCOLOR}=> ${QCOLOR}We created a new ${OUTCOLOR}test-website/config/${QCOLOR} directory.${COLRESET}"
	echo "${PROMPTCOLOR}TASK: ${QCOLOR}Start by moving the ${OUTCOLOR}test-website/.website-config${QCOLOR} dotfile to the ${OUTCOLOR}test-website/config/${QCOLOR} directory. Directly from your ~/workspace directory:${COLRESET}"
	echo -n "${PROMPT}"
	read -r qa1
	if [[ $qa1 =~ (^mv test-website\/.website-config test-website\/config\/?) ]]; then
		mv test-website/.website-config test-website/config
		echo "${PROMPTCOLOR}=> ${ANSCOLOR}Good! The ${OUTCOLOR}.website-config${ANSCOLOR} was moved to the corresponding folder, lets proceed.${COLRESET}"
		addpoints
		question2
	else
		echo "${PROMPTCOLOR}ERROR: ${ERRCOLOR}The ${CMDCOLOR}$qa1${COLRESET}${ERRCOLOR} command will not move the requested file to the requested directory.${COLRESET}"
		substractpoints
		question1
	fi
}