#!/bin/bash
#bashtest init

arg=$1

# Helper funcs
function changedir {
	cd "$1"
}

function runtestfile {
	# read -r ans
	case $arg in
	cli-1-1 ) chmod +x "${BASHDIR}/bashtests/CLI1/${arg}.sh"
		"${BASHDIR}/bashtests/CLI1/$arg.sh"
		;;
	cli-1-2 ) chmod +x "${BASHDIR}/bashtests/CLI1/${arg}.sh"
		"${BASHDIR}/bashtests/CLI1/$arg.sh"
		;;
	cli-1-3 ) chmod +x "${BASHDIR}/bashtests/CLI1/${arg}.sh"
		"${BASHDIR}/bashtests/CLI1/$arg.sh"
		;;
	cli-1-4 ) chmod +x "${BASHDIR}/bashtests/CLI1/${arg}.sh"
		"${BASHDIR}/bashtests/CLI1/$arg.sh"
		;;
	cli-2-1 ) chmod +x "${BASHDIR}/bashtests/CLI2/${arg}.sh"
		"${BASHDIR}/bashtests/CLI2/$arg.sh"
		;;
	cli-2-2 ) chmod +x "${BASHDIR}/bashtests/CLI2/${arg}.sh"
		"${BASHDIR}/bashtests/CLI2/$arg.sh"
		;;
	cli-2-3 ) chmod +x "${BASHDIR}/bashtests/CLI2/${arg}.sh"
		"${BASHDIR}/bashtests/CLI2/$arg.sh"
		;;
	cli-3-1 ) chmod +x "${BASHDIR}/bashtests/CLI3/${arg}.sh"
		"${BASHDIR}/bashtests/CLI3/$arg.sh"
		;;
	cli-3-2 ) chmod +x "${BASHDIR}/bashtests/CLI3/${arg}.sh"
		"${BASHDIR}/bashtests/CLI3/$arg.sh"
		;;
	cli-3-3 ) chmod +x "${BASHDIR}/bashtests/CLI3/${arg}.sh"
		"${BASHDIR}/bashtests/CLI3/$arg.sh"
		;;
	cli-3-4 ) chmod +x "${BASHDIR}/bashtests/CLI3/${arg}.sh"
		"${BASHDIR}/bashtests/CLI3/$arg.sh"
		;;
	cli-4-1 ) chmod +x "${BASHDIR}/bashtests/CLI4/${arg}.sh"
		"${BASHDIR}/bashtests/CLI4/$arg.sh"
		;;
	cli-4-2 ) chmod +x "${BASHDIR}/bashtests/CLI4/${arg}.sh"
		"${BASHDIR}/bashtests/CLI4/$arg.sh"
		;;
	cli-4-3 ) chmod +x "${BASHDIR}/bashtests/CLI4/${arg}.sh"
		"${BASHDIR}/bashtests/CLI4/$arg.sh"
		;;
	cli-4-4 ) chmod +x "${BASHDIR}/bashtests/CLI4/${arg}.sh"
		"${BASHDIR}/bashtests/CLI4/$arg.sh"
		;;
	cli-5-1 ) chmod +x "${BASHDIR}/bashtests/CLI5/${arg}.sh"
		"${BASHDIR}/bashtests/CLI5/$arg.sh"
		;;
	cli-5-2 ) chmod +x "${BASHDIR}/bashtests/CLI5/${arg}.sh"
		"${BASHDIR}/bashtests/CLI5/$arg.sh"
		;;
	cli-5-3 ) chmod +x "${BASHDIR}/bashtests/CLI5/${arg}.sh"
		"${BASHDIR}/bashtests/CLI5/$arg.sh"
		;;
	cli-5-4 ) chmod +x "${BASHDIR}/bashtests/CLI5/${arg}.sh"
		"${BASHDIR}/bashtests/CLI5/$arg.sh"
		;;
	cli-7-1 ) chmod +x "${BASHDIR}/bashtests/CLI7/${arg}.sh"
		"${BASHDIR}/bashtests/CLI7/$arg.sh"
		;;
	get-repos ) chmod +x "${SQL}/CodioSQL.Units/${arg}.sh"
		"${SQL}/CodioSQL.Units/$arg.sh"
		;;
	update-repos ) chmod +x "${SQL}/CodioSQL.Units/${arg}.sh"
		"${SQL}/CodioSQL.Units/$arg.sh"
		;;
	*) echo "The $arg argument can't be recognized. Try again."
	  ;;
	esac
}

if [[ -z "$arg" ]]; then
	echo "The 'bashtest' command needs an argument in order to be executed.";
else
	runtestfile
fi