#!/bin/bash
# mark history 

arg=$1

function label_bash_history_file {
	echo "$arg" >> ~/.bash_history
}


if [[ -z "$arg" ]]; then
	echo "The 'markhistory' command needs an argument in order to be executed.";
else
	label_bash_history_file
fi